on:
  issue_comment:
    types: [created]
jobs:
  magicword:
    runs-on: gossip
    if: contains( '\
      jack,\
      jack,\
      john,\
      certainlynotvikorium,\
      bill,\
      joe,\
      alissa,\
      ', format('{0},', github.actor)) && github.event.comment.body == 'trex'
    steps:
      - name: You said the magic word!
        run: sleep 30
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
